import { ContentBoxCreator } from "../../../contentBox";
import { SpecialText } from "../../../specialText";

export const ExpoContent = [
    ContentBoxCreator.fromObject({references:[{rawContent:"Expo Log",isLatex:false,classes:""},{rawContent:"เลขยกกำลัง",isLatex:false,classes:""},{rawContent:"Exponentail",isLatex:false,classes:""},{rawContent:"สมบัติExpo",isLatex:false,classes:""}],title:{rawContent:"สมบัติเลขยกกำลังของExpo",isLatex:false,classes:""},table:[[{rawContent:"ลำดับสูตร",isLatex:true,classes:"w-full text-center"},{rawContent:"สูตร",isLatex:true,classes:"w-full text-center"}],[[{rawContent:"สูตรที่ 1",isLatex:true,classes:"w-full text-center"},{rawContent:"$a^m \\times a^n$ = $a^{m+n}$",isLatex:true,classes:""}],[{rawContent:"สูตรที่ 2",isLatex:true,classes:"w-full text-center"},{rawContent:"$\\frac{a^m}{a^n}$ = $a^{m-n}$",isLatex:true,classes:""}],[{rawContent:"สูตรที่ 3",isLatex:true,classes:"w-full text-center"},{rawContent:"$(a^m)^n$ = $a^{mn}$",isLatex:true,classes:""}],[{rawContent:"สูตรที่ 4",isLatex:true,classes:"w-full text-center"},{rawContent:"$(ab)^n$ = $a^nb^n$",isLatex:true,classes:""}],[{rawContent:"สูตรที่ 5",isLatex:true,classes:"w-full text-center"},{rawContent:"$(\\frac{a}{b})^n$ = $\\frac{a^n}{b^n}$",isLatex:true,classes:""}],[{rawContent:"สูตรที่ 6",isLatex:true,classes:"w-full text-center"},{rawContent:"$a^0$ = $1$",isLatex:true,classes:""}],[{rawContent:"สูตรที่ 7",isLatex:true,classes:"w-full text-center"},{rawContent:"$a^{-n}$ = $\\frac{1}{a^n}$",isLatex:true,classes:""}],[{rawContent:"สูตรที่ 8",isLatex:true,classes:"w-full text-center"},{rawContent:"$a^{\\frac{m}{n}}$ = $\\sqrt[n]{a^m}$",isLatex:true,classes:""}]]]}),
    
    ContentBoxCreator.fromObject({references:[{rawContent:"Expo Log",isLatex:false,classes:""},{rawContent:"Exponentail",isLatex:false,classes:""},{rawContent:"สมการ",isLatex:false,classes:""}],title:{rawContent:"การแก้สมการ Expo",isLatex:false,classes:""},description:{rawContent:"การแก้สมการเมื่อฐานเท่ากัน",isLatex:false,classes:""},equation:{rawContent:"เมื่อ $a^m = a^n$ สรุปได้ว่า $m=n$",isLatex:true,classes:""}}),
    
    ContentBoxCreator.fromObject({references:[{rawContent:"Expo Log",isLatex:false,classes:""},{rawContent:"Exponential",isLatex:false,classes:""},{rawContent:"อสมการ",isLatex:false,classes:""}],title:{rawContent:"การแก้อสมการ Expo 1",isLatex:false,classes:""},description:{rawContent:"$0<a<1$ (ฟังก์ชันลด)",isLatex:true,classes:""},equation:{rawContent:"ถ้า $a^m > a^n$ แล้ว $m < n$",isLatex:true,classes:""}}),
    
    ContentBoxCreator.fromObject({references:[{rawContent:"Expo Log",isLatex:false,classes:""},{rawContent:"Exponential",isLatex:false,classes:""},{rawContent:"อสมการ",isLatex:false,classes:""}],title:{rawContent:"การแก้อสมการ Expo 2",isLatex:false,classes:""},description:{rawContent:"$0<a<1$ (ฟังก์ชันลด)",isLatex:true,classes:""},equation:{rawContent:"ถ้า $a^m < a^n$ แล้ว $m > n$",isLatex:true,classes:""}}),
    
    ContentBoxCreator.fromObject({references:[{rawContent:"Expo Log",isLatex:false,classes:""},{rawContent:"Exponential",isLatex:false,classes:""},{rawContent:"อสมการ",isLatex:false,classes:""}],title:{rawContent:"การแก้อสมการ Expo 3",isLatex:false,classes:""},description:{rawContent:"$a>1$ (ฟังก์ชันเพิ่ม)",isLatex:true,classes:""},equation:{rawContent:"ถ้า $a^m > a^n$ แล้ว $m > n$",isLatex:true,classes:""}}),
    
    ContentBoxCreator.fromObject({references:[{rawContent:"Expo Log",isLatex:false,classes:""},{rawContent:"Exponential",isLatex:false,classes:""}],title:{rawContent:"การแก้อสมการ Expo 4",isLatex:false,classes:""},description:{rawContent:"$a>1$ (ฟังก์ชันเพิ่ม)",isLatex:true,classes:""},equation:{rawContent:"ถ้า $a^m < a^n$ แล้ว $m < n$",isLatex:true,classes:""}}),
    
    ContentBoxCreator.fromObject({references:[{rawContent:"Expo Log",isLatex:false,classes:""},{rawContent:"เลขยกกำลัง",isLatex:false,classes:""},{rawContent:"Logarithm",isLatex:false,classes:""},{rawContent:"สมบัติLog",isLatex:false,classes:""}],title:{rawContent:"สมบัติเลขยกกำลังของLog",isLatex:false,classes:""},table:[[{rawContent:"ลำดับสูตร",isLatex:true,classes:"w-full text-center"},{rawContent:"สูตร",isLatex:true,classes:"w-full text-center"}],[[{rawContent:"สูตรที่ 1",isLatex:true,classes:"w-full text-center"},{rawContent:"ถ้า $\\log_am=n$ แล้ว $m = a^n$",isLatex:true,classes:""}],[{rawContent:"สูตรที่ 2",isLatex:true,classes:"w-full text-center"},{rawContent:"$log_a 1 = 0$",isLatex:true,classes:""}],[{rawContent:"สูตรที่ 3",isLatex:true,classes:"w-full text-center"},{rawContent:"$\\log_aa = 1$",isLatex:true,classes:""}],[{rawContent:"สูตรที่ 4",isLatex:true,classes:"w-full text-center"},{rawContent:"$loga = \\log_{10}a$",isLatex:true,classes:""}],[{rawContent:"สูตรที่ 5",isLatex:true,classes:"w-full text-center"},{rawContent:"$lnx = \\log_ex$",isLatex:true,classes:""}],[{rawContent:"สูตรที่ 6",isLatex:true,classes:"w-full text-center"},{rawContent:"$\\log_am + \\log_an = \\log_amn$",isLatex:true,classes:""}],[{rawContent:"สูตรที่ 7",isLatex:true,classes:"w-full text-center"},{rawContent:"$\\log_am - \\log_an = \\log_a\\frac{m}{n}$",isLatex:true,classes:""}],[{rawContent:"สูตรที่ 8",isLatex:true,classes:"w-full text-center"},{rawContent:"$\\log_am^p = p\\cdot\\log_am$",isLatex:true,classes:""}],[{rawContent:"สูตรที่ 9",isLatex:true,classes:"w-full text-center"},{rawContent:"$\\log_{a^p}m = \\frac{1}{p}\\cdot\\log_am$",isLatex:true,classes:""}],[{rawContent:"สูตรที่ 10",isLatex:true,classes:"w-full text-center"},{rawContent:"$\\log_ab = \\frac{logb}{loga}$",isLatex:true,classes:""}],[{rawContent:"สูตรที่ 11",isLatex:true,classes:"w-full text-center"},{rawContent:"$a^{log_am} = m$",isLatex:true,classes:""}]]]}), 
    
    ContentBoxCreator.fromObject({references:[{rawContent:"Expo Log",isLatex:false,classes:""},{rawContent:"Logarithm",isLatex:false,classes:""},{rawContent:"สมการ",isLatex:false,classes:""}],title:{rawContent:"การแก้สมการ log 1",isLatex:false,classes:""},description:{rawContent:"การแก้สมการทั่วไป",isLatex:false,classes:""},equation:{rawContent:"เมื่อ $\\log_ax = m$ สรุปได้ว่า $x=a^m$",isLatex:true,classes:""}}),
    
    ContentBoxCreator.fromObject({references:[{rawContent:"Expo Log",isLatex:false,classes:""},{rawContent:"Logarithm",isLatex:false,classes:""},{rawContent:"สมการ",isLatex:false,classes:""}],title:{rawContent:"การแก้สมการ log 2",isLatex:false,classes:""},description:{rawContent:"การแก้สมการเมื่อฐานเท่ากัน",isLatex:false,classes:""},equation:{rawContent:"เมื่อ $\\log_am = \\log_an$ สรุปได้ว่า $m=n$",isLatex:true,classes:""}}),
    
    ContentBoxCreator.fromObject({references:[{rawContent:"Expo Log",isLatex:false,classes:""},{rawContent:"Logarithm",isLatex:false,classes:""},{rawContent:"อสมการ",isLatex:false,classes:""}],title:{rawContent:"การแก้อสมการ log 1",isLatex:false,classes:""},description:{rawContent:"$0<a<1$ (ฟังก์ชันลด)",isLatex:true,classes:""},equation:{rawContent:"ถ้า $\\log_am > \\log_an$ แล้ว $m < n$",isLatex:true,classes:""}}),
    
    ContentBoxCreator.fromObject({references:[{rawContent:"Expo Log",isLatex:false,classes:""},{rawContent:"Logarithm",isLatex:false,classes:""},{rawContent:"อสมการ",isLatex:false,classes:""}],title:{rawContent:"การแก้อสมการ log 2",isLatex:false,classes:""},description:{rawContent:"$0<a<1$ (ฟังก์ชันลด)",isLatex:true,classes:""},equation:{rawContent:"ถ้า $\\log_am < \\log_an$ แล้ว $m > n$",isLatex:true,classes:""}}),
    
    ContentBoxCreator.fromObject({references:[{rawContent:"Expo Log",isLatex:false,classes:""},{rawContent:"Logarithm",isLatex:false,classes:""},{rawContent:"อสมการ",isLatex:false,classes:""}],title:{rawContent:"การแก้อสมการ log 3",isLatex:false,classes:""},description:{rawContent:"$a>1$ (ฟังก์ชันเพิ่ม)",isLatex:true,classes:""},equation:{rawContent:"ถ้า $\\log_am > \\log_an$ แล้ว $m > n$",isLatex:true,classes:""}}),
    
    ContentBoxCreator.fromObject({references:[{rawContent:"Expo Log",isLatex:false,classes:""},{rawContent:"Logarithm",isLatex:false,classes:""},{rawContent:"อสมการ",isLatex:false,classes:""}],title:{rawContent:"การแก้อสมการ log 4",isLatex:false,classes:""},description:{rawContent:"$a>1$ (ฟังก์ชันเพิ่ม)",isLatex:true,classes:""},equation:{rawContent:"ถ้า $\\log_am < \\log_an$ แล้ว $m < n$",isLatex:true,classes:""}})
    
]