import { ContentBoxCreator } from "../../../contentBox";
import { SpecialText } from "../../../specialText";

export const LogicContent = [
    ContentBoxCreator.fromObject({
        references:[{rawContent:"ตรรกศาสตร์",isLatex:false,classes:""},{rawContent:"ประพจน์",isLatex:false,classes:""}],title:{rawContent:"ประพจน์",isLatex:false,classes:""},description:{rawContent:"ประโยคหรือข้อความที่เป็น \"จริง\" หรือ \"เท็จ\" อย่างใดอย่างหนึ่งเท่านั้น มักใช้สัญลักษณ์ $p$ $q$ และ $r$ แทนประพจน์",isLatex:true,classes:""}}),
    
    ContentBoxCreator.fromObject({
        references:[{rawContent:"ตรรกศาสตร์",isLatex:false,classes:""},{rawContent:"ประพจน์",isLatex:false,classes:""},{rawContent:"ตารางค่าความจริง",isLatex:false,classes:""}],title:{rawContent:"การเชื่อมประพจน์ และตารางค่าความจริง",isLatex:false,classes:""},table:[[{rawContent:"$p$",isLatex:true,classes:"w-full text-center"},{rawContent:"$q$",isLatex:true,classes:"w-full text-center"},{rawContent:"$\\sim p$",isLatex:true,classes:"w-full text-center"},{rawContent:"$p \\land q$",isLatex:true,classes:"w-full text-center"},{rawContent:"$p \\lor q$",isLatex:true,classes:"w-full text-center"},{rawContent:"$p \\rightarrow q$",isLatex:true,classes:"w-full text-center"},{rawContent:"$p \\leftrightarrow q$",isLatex:true,classes:"w-full text-center"}],[[{rawContent:"$T$",isLatex:true,classes:"w-full text-center"},{rawContent:"$T$",isLatex:true,classes:"w-full text-center"},{rawContent:"$F$",isLatex:true,classes:"w-full text-center"},{rawContent:"$T$",isLatex:true,classes:"w-full text-center"},{rawContent:"$T$",isLatex:true,classes:"w-full text-center"},{rawContent:"$T$",isLatex:true,classes:"w-full text-center"},{rawContent:"$T$",isLatex:true,classes:"w-full text-center"}],[{rawContent:"$T$",isLatex:true,classes:"w-full text-center"},{rawContent:"$F$",isLatex:true,classes:"w-full text-center"},{rawContent:"$F$",isLatex:true,classes:"w-full text-center"},{rawContent:"$F$",isLatex:true,classes:"w-full text-center"},{rawContent:"$T$",isLatex:true,classes:"w-full text-center"},{rawContent:"$F$",isLatex:true,classes:"w-full text-center"},{rawContent:"$F$",isLatex:true,classes:"w-full text-center"}],[{rawContent:"$F$",isLatex:true,classes:"w-full text-center"},{rawContent:"$T$",isLatex:true,classes:"w-full text-center"},{rawContent:"$T$",isLatex:true,classes:"w-full text-center"},{rawContent:"$F$",isLatex:true,classes:"w-full text-center"},{rawContent:"$T$",isLatex:true,classes:"w-full text-center"},{rawContent:"$T$",isLatex:true,classes:"w-full text-center"},{rawContent:"$F$",isLatex:true,classes:"w-full text-center"}],[{rawContent:"$F$",isLatex:true,classes:"w-full text-center"},{rawContent:"$F$",isLatex:true,classes:"w-full text-center"},{rawContent:"$T$",isLatex:true,classes:"w-full text-center"},{rawContent:"$F$",isLatex:true,classes:"w-full text-center"},{rawContent:"$F$",isLatex:true,classes:"w-full text-center"},{rawContent:"$T$",isLatex:true,classes:"w-full text-center"},{rawContent:"$T$",isLatex:true,classes:"w-full text-center"}]]],definition:[[{rawContent:"$\\land$",isLatex:true,classes:""},{rawContent:"และ",isLatex:false,classes:""}],[{rawContent:"$\\lor$",isLatex:true,classes:""},{rawContent:"หรือ",isLatex:false,classes:""}],[{rawContent:"$\\rightarrow$",isLatex:true,classes:""},{rawContent:"ถ้า...แล้ว....",isLatex:false,classes:""}],[{rawContent:"$\\leftrightarrow$",isLatex:true,classes:""},{rawContent:"ก็ต่อเมื่อ",isLatex:false,classes:""}],[{rawContent:"$\\sim$",isLatex:true,classes:""},{rawContent:"นิเสธ",isLatex:false,classes:""}]]}),
    
    ContentBoxCreator.fromObject({
        references:[{rawContent:"ตรรกศาสตร์",isLatex:false,classes:""},{rawContent:"การดำเนินการทางตรรกศาสตร์",isLatex:false,classes:""},{rawContent:"สมบัตินิเสธ",isLatex:false,classes:""}],title:{rawContent:"สมบัตินิเสธ",isLatex:false,classes:""},definition:[[{rawContent:"$\\equiv$",isLatex:true,classes:""},{rawContent:"สมมูล",isLatex:false,classes:""}], [{rawContent:"$\\sim$",isLatex:true,classes:""},{rawContent:"นิเสธ", isLatex:"false", classes:""}]],keywords:[{rawContent:"สมบัติตรรกศาสตร์",isLatex:false,classes:""},{rawContent:"สมมูล",isLatex:false,classes:""},{rawContent:"นิเสธ",isLatex:false,classes:""}],equation:{rawContent:"$\\sim ( \\sim p ) \\equiv p$",isLatex:true,classes:""}}),
    
    ContentBoxCreator.fromObject({
        references:[{rawContent:"ตรรกศาสตร์",isLatex:false,classes:""},{rawContent:"การดำเนินการทางตรรกศาสตร์",isLatex:false,classes:""},{rawContent:"สมบัติการสลับที่",isLatex:false,classes:""}],title:{rawContent:"สมบัติการสลับที่ \"และ\"",isLatex:true,classes:""},equation:{rawContent:"$p \\land q \\equiv q \\land p$",isLatex:true,classes:""},definition:[[{rawContent:"$\\equiv$",isLatex:true,classes:""},{rawContent:"สมมูล",isLatex:false,classes:""}],[{rawContent:"$\\land$",isLatex:true,classes:""},{rawContent:"และ",isLatex:false,classes:""}]],keywords:[{rawContent:"และ",isLatex:false,classes:""}, {rawContent:"สมมูล", isLatex:"false", classes:""}]}),

    ContentBoxCreator.fromObject({
        references:[{rawContent:"ตรรกศาสตร์",isLatex:false,classes:""},{rawContent:"การดำเนินการทางตรรกศาสตร์",isLatex:false,classes:""},{rawContent:"สมบัติการสลับที่",isLatex:false,classes:""}],title:{rawContent:"สมบัติการสลับที่ \"หรือ\"",isLatex:true,classes:""},equation:{rawContent:"$p \\lor q \\equiv q \\lor p$",isLatex:true,classes:""},definition:[[{rawContent:"$\\equiv$",isLatex:true,classes:""},{rawContent:"สมมูล",isLatex:false,classes:""}],[{rawContent:"$\\lor$",isLatex:true,classes:""},{rawContent:"หรือ",isLatex:false,classes:""}]],keywords:[{rawContent:"หรือ",isLatex:false,classes:""},{rawContent:"สมมูล",isLatex:false,classes:""}]}),

    ContentBoxCreator.fromObject({
        references:[{rawContent:"ตรรกศาสตร์",isLatex:false,classes:""},{rawContent:"การดำเนินการทางตรรกศาสตร์",isLatex:false,classes:""},{rawContent:"สมบัติการสลับที่",isLatex:false,classes:""}],title:{rawContent:"สมบัติการสลับที่ \"ก็ต่อเมื่อ\"",isLatex:true,classes:""},equation:{rawContent:"$p \\leftrightarrow q \\equiv q \\leftrightarrow p$",isLatex:true,classes:""},definition:[[{rawContent:"$\\equiv$",isLatex:true,classes:""},{rawContent:"สมมูล",isLatex:false,classes:""}],[{rawContent:"$\\leftrightarrow$",isLatex:true,classes:""},{rawContent:"ก็ต่อเมื่อ",isLatex:false,classes:""}]],keywords:[{rawContent:"ก็ต่อเมื่อ",isLatex:false,classes:""},{rawContent:"สมมูล",isLatex:false,classes:""}]}),
    
    ContentBoxCreator.fromObject({
        references:[{rawContent:"ตรรกศาสตร์",isLatex:false,classes:""},{rawContent:"การดำเนินการทางตรรกศาสตร์",isLatex:false,classes:""},{rawContent:"สมบัติการกระจาย",isLatex:false,classes:""}],title:{rawContent:"สมบัติการกระจาย \"และ\" ไป \"หรือ\"",isLatex:true,classes:""},equation:{rawContent:"$p \\land  ( q \\lor r ) \\equiv ( p \\land q) \\lor (p \\lor r)$",isLatex:true,classes:""},definition:[[{rawContent:"$\\equiv$",isLatex:true,classes:""},{rawContent:"สมมูล",isLatex:false,classes:""}],[{rawContent:"$\\land$",isLatex:true,classes:""},{rawContent:"และ",isLatex:false,classes:""}],[{rawContent:"$\\lor$",isLatex:true,classes:""},{rawContent:"หรือ",isLatex:false,classes:""}]],keywords:[{rawContent:"และ",isLatex:false,classes:""},{rawContent:"สมมูล",isLatex:false,classes:""},{rawContent:"หรือ",isLatex:false,classes:""}]}),
    
    ContentBoxCreator.fromObject({
        references:[{rawContent:"ตรรกศาสตร์",isLatex:false,classes:""},{rawContent:"การดำเนินการทางตรรกศาสตร์",isLatex:false,classes:""},{rawContent:"สมบัติการกระจาย",isLatex:false,classes:""}],title:{rawContent:"สมบัติการกระจาย \"หรือ\" ไป \"และ\"",isLatex:true,classes:""},equation:{rawContent:"$p \\lor  ( q \\land r ) \\equiv ( p \\lor q) \\land (p \\lor r)$",isLatex:true,classes:""},definition:[[{rawContent:"$\\equiv$",isLatex:true,classes:""},{rawContent:"สมมูล",isLatex:false,classes:""}],[{rawContent:"$\\land$",isLatex:true,classes:""},{rawContent:"และ",isLatex:false,classes:""}],[{rawContent:"$\\lor$",isLatex:true,classes:""},{rawContent:"หรือ",isLatex:false,classes:""}]],keywords:[{rawContent:"และ",isLatex:false,classes:""},{rawContent:"สมมูล",isLatex:false,classes:""},{rawContent:"หรือ",isLatex:false,classes:""}]}),

    ContentBoxCreator.fromObject({
        references:[{rawContent:"ตรรกศาสตร์",isLatex:false,classes:""},{rawContent:"การดำเนินการทางตรรกศาสตร์",isLatex:false,classes:""},{rawContent:"สมบัติ \"ถ้า...แล้ว...\"",isLatex:false,classes:""}],title:{rawContent:"สมบัติ \"ถ้า...แล้ว...\"",isLatex:false,classes:""},equation:{rawContent:"$p \\rightarrow q \\equiv $ $\\sim p \\lor q$ $\\equiv$ $\\sim q \\rightarrow$ $\\sim p$",isLatex:true,classes:""},definition:[[{rawContent:"$\\equiv$",isLatex:true,classes:""},{rawContent:"สมมูล",isLatex:false,classes:""}],[{rawContent:"$\\rightarrow$",isLatex:true,classes:""},{rawContent:"ถ้า...แล้ว...",isLatex:false,classes:""}],[{rawContent:"$\\sim$",isLatex:true,classes:""},{rawContent:"นิเสธ",isLatex:false,classes:""}],[{rawContent:"$\\lor$",isLatex:true,classes:""},{rawContent:"หรือ",isLatex:false,classes:""}]],keywords:[{rawContent:"ถ้าแล้ว",isLatex:false,classes:""},{rawContent:"ถ้า...แล้ว...",isLatex:false,classes:""}]}),
    
    ContentBoxCreator.fromObject({
        references:[{rawContent:"ตรรกศาสตร์",isLatex:false,classes:""},{rawContent:"การดำเนินการทางตรรกศาสตร์",isLatex:false,classes:""},{rawContent:"สมบัติ \"ก็ต่อเมื่อ\"",isLatex:false,classes:""}],title:{rawContent:"สมบัติ \"ก็ต่อเมื่อ\"",isLatex:false,classes:""},equation:{rawContent:"$p \\leftrightarrow q \\equiv $ $( p \\rightarrow q) \\land (q \\rightarrow p)$",isLatex:true,classes:""},definition:[[{rawContent:"$\\equiv$",isLatex:true,classes:""},{rawContent:"สมมูล",isLatex:false,classes:""}],[{rawContent:"$\\leftrightarrow$",isLatex:true,classes:""},{rawContent:"ก็ต่อเมื่อ",isLatex:false,classes:""}],[{rawContent:"$\\rightarrow$",isLatex:true,classes:""},{rawContent:"ถ้า...แล้ว...",isLatex:false,classes:""}],[{rawContent:"$\\land$",isLatex:true,classes:""},{rawContent:"และ",isLatex:false,classes:""}]],keywords:[{rawContent:"ก็ต่อเมื่อ",isLatex:false,classes:""}]}),

    ContentBoxCreator.fromObject({
        references:[{rawContent:"ตรรกศาสตร์",isLatex:false,classes:""},{rawContent:"การดำเนินการทางตรรกศาสตร์",isLatex:false,classes:""},{rawContent:"การกระจายนิเสธ",isLatex:false,classes:""}],title:{rawContent:"การกระจายนิเสธ \"และ\"",isLatex:false,classes:""},equation:{rawContent:"$\\sim (p \\land q)$ $\\equiv$ $\\sim p \\lor \\sim q $",isLatex:true,classes:""},definition:[[{rawContent:"$\\equiv$",isLatex:true,classes:""},{rawContent:"สมมูล",isLatex:false,classes:""}],[{rawContent:"$\\sim$",isLatex:true,classes:""},{rawContent:"นิเสธ",isLatex:false,classes:""}],[{rawContent:"$\\land$",isLatex:true,classes:""},{rawContent:"และ",isLatex:false,classes:""}],[{rawContent:"$\\lor$",isLatex:true,classes:""},{rawContent:"หรือ",isLatex:false,classes:""}]],keywords:[{rawContent:"กระจายนิเสธ",isLatex:false,classes:""},{rawContent:"นิเสธ",isLatex:false,classes:""},{rawContent:"และ",isLatex:false,classes:""}]}),

    ContentBoxCreator.fromObject({
        references:[{rawContent:"ตรรกศาสตร์",isLatex:false,classes:""},{rawContent:"การดำเนินการทางตรรกศาสตร์",isLatex:false,classes:""},{rawContent:"การกระจายนิเสธ",isLatex:false,classes:""}],title:{rawContent:"การกระจายนิเสธ \"หรือ\"",isLatex:false,classes:""},equation:{rawContent:"$\\sim (p \\lor q)$ $\\equiv$ $\\sim p \\land \\sim q $",isLatex:true,classes:""},definition:[[{rawContent:"$\\equiv$",isLatex:true,classes:""},{rawContent:"สมมูล",isLatex:false,classes:""}],[{rawContent:"$\\sim$",isLatex:true,classes:""},{rawContent:"นิเสธ",isLatex:false,classes:""}],[{rawContent:"$\\land$",isLatex:true,classes:""},{rawContent:"และ",isLatex:false,classes:""}],[{rawContent:"$\\lor$",isLatex:true,classes:""},{rawContent:"หรือ",isLatex:false,classes:""}]],keywords:[{rawContent:"กระจายนิเสธ",isLatex:false,classes:""},{rawContent:"นิเสธ",isLatex:false,classes:""},{rawContent:"หรือ",isLatex:false,classes:""}]}),
    
    ContentBoxCreator.fromObject({
        references:[{rawContent:"ตรรกศาสตร์",isLatex:false,classes:""},{rawContent:"การดำเนินการทางตรรกศาสตร์",isLatex:false,classes:""},{rawContent:"การกระจายนิเสธ",isLatex:false,classes:""}],title:{rawContent:"การกระจายนิเสธ \"ก็ต่อเมื่อ\"",isLatex:false,classes:""},equation:{rawContent:"$\\sim (p \\leftrightarrow q)$ $\\equiv$ $\\sim p \\leftrightarrow q $ $\\equiv$ $p \\leftrightarrow \\sim q$",isLatex:true,classes:""},definition:[[{rawContent:"$\\equiv$",isLatex:true,classes:""},{rawContent:"สมมูล",isLatex:false,classes:""}],[{rawContent:"$\\sim$",isLatex:true,classes:""},{rawContent:"นิเสธ",isLatex:false,classes:""}],[{rawContent:"$\\leftrightarrow$",isLatex:true,classes:""},{rawContent:"ก็ต่อเมื่อ",isLatex:false,classes:""}]],keywords:[{rawContent:"กระจายนิเสธ",isLatex:false,classes:""},{rawContent:"นิเสธ",isLatex:false,classes:""},{rawContent:"ก็ต่อเมื่อ",isLatex:false,classes:""}]}),
    
    ContentBoxCreator.fromObject({
        references:[{rawContent:"ตรรกศาสตร์",isLatex:false,classes:""},{rawContent:"สัจนิรันดร์",isLatex:false,classes:""}],title:{rawContent:"สัจนิรันดร์",isLatex:false,classes:""},description:{rawContent:"สัจนิรันดร์ คือ รูปแบบของประพจน์ที่มีค่าความจริงเป็นจริงทุกกรณี หาโดย $!break!$ วิธีการหาข้อขัดแย้ง เป็นวิธีการเพื่อหาว่ารูปแบบของประพจน์ที่กำหนดจะเป็นเท็จในกรณีใดได้บ้าง ถ้าพบว่ามีกรณีที่เป็นเท็จได้ จะสรุปว่ารูปแบบของประพจน์ไม่เป็นสัจนิรันดร์ แต่หากพบข้อขัดแย้งระหว่างที่พยายามทำให้ประพจน์มีค่าเป็นเท็จ แสดงว่ารูปแบบของประพจน์นั้นไม่สามารถเป็นเท็จได้ แปลว่าต้องเป็นจริงเสมอ จึงสรุปได้ว่ารูปแบบของประพจน์เป็นสัจนิรันดร์",isLatex:true,classes:""},image:"https://lh3.googleusercontent.com/proxy/bPuou1xlrIR7R71EYiDl5g-XQMA0lwxZSSyrx1iRo-paFNlQpTLIi7wzHSUaFSSStcG_djtNT-H0DWDqxY5-F_VqO2g44CCiPFlt_Yo6-466Gm2Y7pSvHQUtDW-D6_ry2YhwbsBL"}),    
    
    ContentBoxCreator.fromObject({
        references:[{rawContent:"ตรรกศาสตร์",isLatex:false,classes:""},{rawContent:"การอ้างเหตุผล",isLatex:false,classes:""}],title:{rawContent:"การอ้างเหตุผล",isLatex:false,classes:""},description:{rawContent:"ประกอบด้วย เหตุ  $(p_1 ,p_2 ,p_3  , … ,p_n)$ และ ผล $C$ $!break!$ การอ้างเหตุผล จะเชื่อมเหตุแต่ละตัวด้วย “และ” และเชื่อมจากเหตุไปผลด้วย “ถ้า…แล้ว…” $!break!$ การอ้างเหตุผลสมเหตุสมผล (Valid) ก็ต่อเมื่อ รูปแบบของประพจน์เป็นสัจนิรันดร์ $!break!$ และไม่สมเหตุสมผล (Invalid) ก็ต่อเมื่อ รูปแบบของประพจน์ไม่เป็นสัจนิรันดร์",isLatex:true,classes:""},equation:{rawContent:"$p_1 \\land p_2 \\land p_3 \\land ... \\land p_n \\rightarrow C$",isLatex:true,classes:""}}),
    
    
    ]