import { ContentBoxCreator } from "../../../contentBox"

export const ComplexContent = [

    ContentBoxCreator.fromObject({references:[{rawContent:"จำนวนเชิงซ้อน",isLatex:false,classes:""}],title:{rawContent:"การเขียนจำนวนเชิงซ้อน",isLatex:true,classes:""},description:{rawContent:"สำหรับจำนวนเชิงซ้อน  $z$ = $( a , b )$ หรือ $z = a + bi$ เมื่อ   $a$ และ   $b$ เป็นจำนวนจริง$!break!$เรียกส่วน $a$ ว่าส่วนจริง และ ส่วน $b$ ว่าส่วนจินตภาพ",isLatex:true,classes:""},equation:{rawContent:"$z = a + bi$",isLatex:true,classes:""},definition:[[{rawContent:"เมื่อ $i^{2} = -1$",isLatex:true,classes:""},{rawContent:"",isLatex:false,classes:""}]]
}),
    ContentBoxCreator.fromObject({references:[{rawContent:"จำนวนเชิงซ้อน",isLatex:false,classes:""}],title:{rawContent:"การบวกลบจำนวนเชิงซ้อน",isLatex:false,classes:""},equation:{rawContent:"$(a+bi) \\pm (c+di) = (a\\pm c)  + (b\\pm d)i$",isLatex:true,classes:""},description:{rawContent:"นำส่วนจริงบวกลบกับส่วนจริง และ ส่วนจินตภาพบวกลบกับส่วนจินตภาพ",isLatex:false,classes:""}
}),
    ContentBoxCreator.fromObject({references:[{rawContent:"จำนวนเชิงซ้อน",isLatex:false,classes:""},{rawContent:"สัญลักษณ์ที่เกี่ยวข้อง",isLatex:false,classes:""}],title:{rawContent:"การสังยุค",isLatex:false,classes:""},description:{rawContent:"ถ้า ${\\displaystyle z=a+bi\\,} $เป็นจำเชิงนวนซ้อน สังยุคของ  $ {\\displaystyle z} คือ  {\\displaystyle a-bi\\,}$ เราเขียนแทนสังยุคของ  $ {\\displaystyle z} $ด้วย  ${\\displaystyle {\\bar {z}}}$",isLatex:true,classes:""},table:[[{rawContent:"สมบัติการสังยุค",isLatex:true,classes:""}],[[{rawContent:"1.$\\overline{z\\pm w} = \\bar{z} \\pm  \\bar{w}$",isLatex:true,classes:""}],[{rawContent:"2.$\\overline{zw} = \\bar{z}\\bar{w}$",isLatex:true,classes:""}],[{rawContent:"3.$\\overline{(\\frac{z}{w})} = \\frac{\\bar{z}}{\\bar{w}}$",isLatex:true,classes:""}],[{rawContent:"4.$\\left | z \\right |^{2} = z\\bar{z}$",isLatex:true,classes:""}]]],definition:[[{rawContent:"$\\left | z \\right | = \\sqrt{a^{2}+b^{2}}$",isLatex:true,classes:""},{rawContent:"",isLatex:false,classes:""}]]
}),
    ContentBoxCreator.fromObject({references:[{rawContent:"จำนวนเชิงซ้อน",isLatex:false,classes:""}],title:{rawContent:"ขนาดของจำนวนเชิงซ้อน",isLatex:false,classes:""},description:{rawContent:"ขนาดของจำนวนเชิงซ้อน  $ {\\displaystyle z=a+bi\\,} $เขียนแทนด้วย $ {\\displaystyle |z|}$ คือจำนวนจริงที่ไม่เป็นลบ$ {\\displaystyle {\\sqrt {a^{2}+b^{2}}}} $เราอาจแปลความหมายของขนาดของจำนวนเชิงซ้อนได้ว่าเป็นความยาวของเส้นตรงที่ลากจากจุด (0, 0) ไปยังจุด (a, b) บนระบบพิกัดคาร์ทีเซียน ขนาดของจำนวนเชิงซ้อนมีสมบัติสำคัญ ๆ ดังต่อไปนี้",isLatex:true,classes:""},table:[[{rawContent:"สมบัติของขนาด",isLatex:true,classes:""}],[[{rawContent:"1.${\\displaystyle \\left|z\\right\\vert =\\left|{\\bar {z}}\\right\\vert }$",isLatex:true,classes:""}],[{rawContent:"2.${\\displaystyle \\left|z_{1}z_{2}\\right\\vert =\\left|z_{1}\\right\\vert \\left|z_{2}\\right\\vert }$",isLatex:true,classes:""}],[{rawContent:"3.${\\displaystyle \\left|z_{1}+z_{2}\\right\\vert \\leq \\;\\left|z_{1}\\right\\vert +\\left|z_{2}\\right\\vert }$",isLatex:true,classes:""}],[{rawContent:"4.${\\displaystyle \\left|z_{1}-z_{2}\\right\\vert \\geq \\;{\\big |}\\left|z_{1}\\right\\vert -\\left|z_{2}\\right\\vert {\\big |}}$",isLatex:true,classes:""}],[{rawContent:"5.${\\displaystyle \\left|z\\right\\vert =0} $ ก็ต่อเมื่อ  ${\\displaystyle z=0\\,}$",isLatex:true,classes:""}]]]
})

]