import { ContentBoxCreator } from "../../../contentBox"

export const ComplexContent = [

    ContentBoxCreator.fromObject({references:[{rawContent:"จำนวนเชิงซ้อน",isLatex:false,classes:""}],title:{rawContent:"การเขียนจำนวนเชิงซ้อน",isLatex:true,classes:""},description:{rawContent:"สำหรับจำนวนเชิงซ้อน  $z$ = $( a , b )$ หรือ $z = a + bi$ เมื่อ   $a$ และ   $b$ เป็นจำนวนจริง$!break!$เรียกส่วน $a$ ว่าส่วนจริง และ ส่วน $b$ ว่าส่วนจินตภาพ",isLatex:true,classes:""},equation:{rawContent:"$z = a + bi$",isLatex:true,classes:""},definition:[[{rawContent:"เมื่อ $i^{2} = -1$",isLatex:true,classes:""},{rawContent:"",isLatex:false,classes:""}]]
}),
    ContentBoxCreator.fromObject({references:[{rawContent:"จำนวนเชิงซ้อน",isLatex:false,classes:""}],title:{rawContent:"การบวกลบจำนวนเชิงซ้อน",isLatex:false,classes:""},equation:{rawContent:"$(a+bi) \\pm (c+di) = (a\\pm c)  + (b\\pm d)i$",isLatex:true,classes:""},description:{rawContent:"นำส่วนจริงบวกลบกับส่วนจริง และ ส่วนจินตภาพบวกลบกับส่วนจินตภาพ",isLatex:false,classes:""}
}),
    ContentBoxCreator.fromObject({references:[{rawContent:"จำนวนเชิงซ้อน",isLatex:false,classes:""},{rawContent:"สัญลักษณ์ที่เกี่ยวข้อง",isLatex:false,classes:""}],title:{rawContent:"การสังยุค",isLatex:false,classes:""},description:{rawContent:"ถ้า ${\\displaystyle z=a+bi\\,} $เป็นจำเชิงนวนซ้อน สังยุคของ  $ {\\displaystyle z} คือ  {\\displaystyle a-bi\\,}$ เราเขียนแทนสังยุคของ  $ {\\displaystyle z} $ด้วย  ${\\displaystyle {\\bar {z}}}$",isLatex:true,classes:""},table:[[{rawContent:"สมบัติการสังยุค",isLatex:true,classes:""}],[[{rawContent:"1.$\\overline{z\\pm w} = \\bar{z} \\pm  \\bar{w}$",isLatex:true,classes:""}],[{rawContent:"2.$\\overline{zw} = \\bar{z}\\bar{w}$",isLatex:true,classes:""}],[{rawContent:"3.$\\overline{(\\frac{z}{w})} = \\frac{\\bar{z}}{\\bar{w}}$",isLatex:true,classes:""}],[{rawContent:"4.$\\left | z \\right |^{2} = z\\bar{z}$",isLatex:true,classes:""}]]],definition:[[{rawContent:"$\\left | z \\right | = \\sqrt{a^{2}+b^{2}}$",isLatex:true,classes:""},{rawContent:"",isLatex:false,classes:""}]]
}),
    ContentBoxCreator.fromObject({references:[{rawContent:"จำนวนเชิงซ้อน",isLatex:false,classes:""}],title:{rawContent:"ขนาดของจำนวนเชิงซ้อน",isLatex:false,classes:""},description:{rawContent:"ขนาดของจำนวนเชิงซ้อน  $ {\\displaystyle z=a+bi\\,} $เขียนแทนด้วย $ {\\displaystyle |z|}$ คือจำนวนจริงที่ไม่เป็นลบ$ {\\displaystyle {\\sqrt {a^{2}+b^{2}}}} $เราอาจแปลความหมายของขนาดของจำนวนเชิงซ้อนได้ว่าเป็นความยาวของเส้นตรงที่ลากจากจุด (0, 0) ไปยังจุด (a, b) บนระบบพิกัดคาร์ทีเซียน ขนาดของจำนวนเชิงซ้อนมีสมบัติสำคัญ ๆ ดังต่อไปนี้",isLatex:true,classes:""},table:[[{rawContent:"สมบัติของขนาด",isLatex:true,classes:""}],[[{rawContent:"1.${\\displaystyle \\left|z\\right\\vert =\\left|{\\bar {z}}\\right\\vert }$",isLatex:true,classes:""}],[{rawContent:"2.${\\displaystyle \\left|z_{1}z_{2}\\right\\vert =\\left|z_{1}\\right\\vert \\left|z_{2}\\right\\vert }$",isLatex:true,classes:""}],[{rawContent:"3.${\\displaystyle \\left|z_{1}+z_{2}\\right\\vert \\leq \\;\\left|z_{1}\\right\\vert +\\left|z_{2}\\right\\vert }$",isLatex:true,classes:""}],[{rawContent:"4.${\\displaystyle \\left|z_{1}-z_{2}\\right\\vert \\geq \\;{\\big |}\\left|z_{1}\\right\\vert -\\left|z_{2}\\right\\vert {\\big |}}$",isLatex:true,classes:""}],[{rawContent:"5.${\\displaystyle \\left|z\\right\\vert =0} $ ก็ต่อเมื่อ  ${\\displaystyle z=0\\,}$",isLatex:true,classes:""}]]]
}),
    ContentBoxCreator.fromObject({references:[{rawContent:"จำนวนเชิงซ้อน",isLatex:false,classes:""}],title:{rawContent:"การเขียนจำนวนเชิงซ้อนในรูปเชิงขั้ว",isLatex:false,classes:""},description:{rawContent:"จากที่เราเคยเขียนจำนวนเชิงซ้อน  $z=x+yi$ (จำนวนเชิงซ้อนที่ไม่เป็นศูนย์) บนระนาบได้ดังนี้ จากรูป หากเรากำหนดให้ r แทนระยะห่างระหว่างจุดกำเนิด  $O$ กับ $z$ และกำหนดให้ θ แทนขนาดของมุมที่วัดทวนเข็มนาฬิกาจากแกน $X$ ทางด้านบวก ไปยัง $ \\vec{oz} $จะได้ความสัมพันธ์ดังนี้",isLatex:true,classes:""},image:"https://oer.physics.manchester.ac.uk/Math2/Notes/jsmath/argand.png",equation:{rawContent:"จาก  $z=x+yi$ เขียนใหม่ได้เป็น  $ z=r(cosθ+isinθ)$",isLatex:true,classes:""},definition:[[{rawContent:"$x=rcosθ$",isLatex:true,classes:""},{rawContent:"",isLatex:true,classes:""}],[{rawContent:"$y=rsinθ$",isLatex:true,classes:""},[{rawContent:"",isLatex:false,classes:""},{rawContent:"",isLatex:false,classes:""}]],[{rawContent:"$y=\\left | z \\right |=\\sqrt{x^{2}+y^{2}}$",isLatex:true,classes:""},[{rawContent:"",isLatex:false,classes:""},{rawContent:"",isLatex:false,classes:""}]]]
}),
    ContentBoxCreator.fromObject({references:[{rawContent:"จำนวนเชิงซ้อน",isLatex:false,classes:""}],title:{rawContent:"การคูณจำนวนเชิงซ้อน",isLatex:false,classes:""},description:{rawContent:"การคูณจำนวนเชิงซ้อนทำได้โดยการกระจายคูณที่ละพจน์ของจำนวนเชิงซ้อน",isLatex:false,classes:""},equation:{rawContent:"$z_1 \\cdot z_2 = (a_1 + b_1i) \\cdot (a_2 + b_2i) $\\[ = a_1a_2 + a_1b_2i + b_1a_2i + b_1b_2i^2 \\]\\[ = a_1a_2 + (a_1b_2 + b_1a_2)i - b_1b_2 \\]",isLatex:true,classes:""}
}),
    ContentBoxCreator.fromObject({references:[{rawContent:"จำนวนเชิงซ้อน",isLatex:false,classes:""}],title:{rawContent:"การหารจำนวนเชิงซ้อน",isLatex:false,classes:""},description:{rawContent:"การหารจำนวนเชิงซ้อนเราต้องอาศัยวิธีการที่เรียกว่าการ Conjugate มาช่วยซึ่งคือการคูณทั้งตัวเศษและตัวส่วนด้วยสังยุคของตัวส่วน",isLatex:false,classes:""},equation:{rawContent:"\\[ \\frac{z_1}{z_2} = \\frac{a_1 + b_1i}{a_2 + b_2i} \\]  \\[ = \\frac{(a_1 + b_1i) \\cdot (a_2 - b_2i)}{(a_2 + b_2i) \\cdot (a_2 - b_2i)} \\]  \\[ = \\frac{(a_1a_2 + b_1b_2) + (a_2b_1 - a_1b_2)i}{a_2^2 + b_2^2} \\]",isLatex:true,classes:""},keywords:[{rawContent:"conjugate",isLatex:false,classes:""}]
}),
    ContentBoxCreator.fromObject({references:[{rawContent:"จำนวนเชิงซ้อน",isLatex:false,classes:""}],title:{rawContent:"การคำนวณจำนวนเชิงซ้อนในรูปเชิงขั้ว",isLatex:false,classes:""},table:[[{rawContent:"การคำนวณต่างๆ",isLatex:true,classes:""},{rawContent:"",isLatex:false,classes:""}],[[{rawContent:"การคูณ",isLatex:true,classes:""},{rawContent:"$ z_1 \\cdot z_2 = r_1 r_2 (\\cos(\\theta_1 + \\theta_2) + i \\sin(\\theta_1 + \\theta_2)) $",isLatex:true,classes:""}],[{rawContent:"การหาร",isLatex:false,classes:""},{rawContent:"$\\frac{z_1}{z_2} = \\frac{r_1}{r_2} (\\cos(\\theta_1 - \\theta_2) + i \\sin(\\theta_1 - \\theta_2))$",isLatex:true,classes:""}],[{rawContent:"การยกกำลัง",isLatex:false,classes:""},{rawContent:"$ z^n = r^n (\\cos(n\\theta) + i \\sin(n\\theta)) $",isLatex:true,classes:""}],[{rawContent:"การหารากที่ k",isLatex:false,classes:""},{rawContent:"$\\sqrt[k]{z} = \\sqrt[k]{r} (\\cos\\left(\\frac{\\theta+2 \\pi n}{k}\\right) + i \\sin\\left(\\frac{\\theta+2\\pi n}{k}\\right))$ เมื่อ n=0,1,2,...,k-1 ",isLatex:true,classes:""}]]]
}),
    ContentBoxCreator.fromObject({references:[{rawContent:"จำนวนเชิงซ้อน",isLatex:false,classes:""}],title:{rawContent:"Euler's formula",isLatex:false,classes:""},keywords:[{rawContent:"ทฤษฎีบทออยเลอร์",isLatex:false,classes:""}],description:{rawContent:"ใช้ในการคิดคำนวณไฟฟ้ากระแสสลับได้",isLatex:false,classes:""},equation:{rawContent:"\\[ e^{i \\theta} = \\cos \\theta + i \\sin \\theta \\]",isLatex:true,classes:""}
}),

]